### ISSUE TITLE
Defaults funnel placement to 0.00

### ISSUE THREAD

**Issue by kylehamilton** [jsakaluk/ce-funnel#1]
I think I found a bug where the plot centers at 0.00

### load data
dat <- get(data(dat.bonett2010))

### meta-analysis using the raw alpha values
res <- rma(measure="ARAW", ai=ai, mi=mi, ni=ni, data=dat)
res

CE.funnel(res)
![image](https://user-images.githubusercontent.com/2274317/37371602-264afebc-26cd-11e8-870f-b36588b49587.png)

**Comment by jsakaluk** [comment]
According to [the metafor() documentation](http://www.metafor-project.org/doku.php/plots:contour_enhanced_funnel_plot), this is a feature, not a bug of contour-enhanced funnel plots; they are supposed to be centred on zero, as opposed to centred on the estimated effect (as in a traditional funnel plot). This visual feature is thought to make the suppression of null effects more visually obvious.
